import Foundation

struct SupportedLanguage: Identifiable, Hashable {
    let code: String
    let name: String

    var id: String { code }

    /// All languages supported by Soniox cloud transcription & translation (60 languages).
    static let cloudLanguages: [SupportedLanguage] = [
        SupportedLanguage(code: "af", name: "Afrikaans"),
        SupportedLanguage(code: "sq", name: "Albanian"),
        SupportedLanguage(code: "ar", name: "Arabic"),
        SupportedLanguage(code: "az", name: "Azerbaijani"),
        SupportedLanguage(code: "eu", name: "Basque"),
        SupportedLanguage(code: "be", name: "Belarusian"),
        SupportedLanguage(code: "bn", name: "Bengali"),
        SupportedLanguage(code: "bs", name: "Bosnian"),
        SupportedLanguage(code: "bg", name: "Bulgarian"),
        SupportedLanguage(code: "ca", name: "Catalan"),
        SupportedLanguage(code: "zh", name: "Chinese"),
        SupportedLanguage(code: "hr", name: "Croatian"),
        SupportedLanguage(code: "cs", name: "Czech"),
        SupportedLanguage(code: "da", name: "Danish"),
        SupportedLanguage(code: "nl", name: "Dutch"),
        SupportedLanguage(code: "en", name: "English"),
        SupportedLanguage(code: "et", name: "Estonian"),
        SupportedLanguage(code: "fi", name: "Finnish"),
        SupportedLanguage(code: "fr", name: "French"),
        SupportedLanguage(code: "gl", name: "Galician"),
        SupportedLanguage(code: "de", name: "German"),
        SupportedLanguage(code: "el", name: "Greek"),
        SupportedLanguage(code: "gu", name: "Gujarati"),
        SupportedLanguage(code: "he", name: "Hebrew"),
        SupportedLanguage(code: "hi", name: "Hindi"),
        SupportedLanguage(code: "hu", name: "Hungarian"),
        SupportedLanguage(code: "id", name: "Indonesian"),
        SupportedLanguage(code: "it", name: "Italian"),
        SupportedLanguage(code: "ja", name: "Japanese"),
        SupportedLanguage(code: "kn", name: "Kannada"),
        SupportedLanguage(code: "kk", name: "Kazakh"),
        SupportedLanguage(code: "ko", name: "Korean"),
        SupportedLanguage(code: "lv", name: "Latvian"),
        SupportedLanguage(code: "lt", name: "Lithuanian"),
        SupportedLanguage(code: "mk", name: "Macedonian"),
        SupportedLanguage(code: "ms", name: "Malay"),
        SupportedLanguage(code: "ml", name: "Malayalam"),
        SupportedLanguage(code: "mr", name: "Marathi"),
        SupportedLanguage(code: "no", name: "Norwegian"),
        SupportedLanguage(code: "fa", name: "Persian"),
        SupportedLanguage(code: "pl", name: "Polish"),
        SupportedLanguage(code: "pt", name: "Portuguese"),
        SupportedLanguage(code: "pa", name: "Punjabi"),
        SupportedLanguage(code: "ro", name: "Romanian"),
        SupportedLanguage(code: "ru", name: "Russian"),
        SupportedLanguage(code: "sr", name: "Serbian"),
        SupportedLanguage(code: "sk", name: "Slovak"),
        SupportedLanguage(code: "sl", name: "Slovenian"),
        SupportedLanguage(code: "es", name: "Spanish"),
        SupportedLanguage(code: "sw", name: "Swahili"),
        SupportedLanguage(code: "sv", name: "Swedish"),
        SupportedLanguage(code: "tl", name: "Tagalog"),
        SupportedLanguage(code: "ta", name: "Tamil"),
        SupportedLanguage(code: "te", name: "Telugu"),
        SupportedLanguage(code: "th", name: "Thai"),
        SupportedLanguage(code: "tr", name: "Turkish"),
        SupportedLanguage(code: "uk", name: "Ukrainian"),
        SupportedLanguage(code: "ur", name: "Urdu"),
        SupportedLanguage(code: "vi", name: "Vietnamese"),
        SupportedLanguage(code: "cy", name: "Welsh"),
    ]

    /// Languages supported by local Whisper models (subset).
    static let whisperLanguages: [SupportedLanguage] = [
        SupportedLanguage(code: "auto", name: "Auto-detect"),
        SupportedLanguage(code: "af", name: "Afrikaans"),
        SupportedLanguage(code: "ar", name: "Arabic"),
        SupportedLanguage(code: "be", name: "Belarusian"),
        SupportedLanguage(code: "bg", name: "Bulgarian"),
        SupportedLanguage(code: "bn", name: "Bengali"),
        SupportedLanguage(code: "ca", name: "Catalan"),
        SupportedLanguage(code: "cs", name: "Czech"),
        SupportedLanguage(code: "cy", name: "Welsh"),
        SupportedLanguage(code: "da", name: "Danish"),
        SupportedLanguage(code: "de", name: "German"),
        SupportedLanguage(code: "el", name: "Greek"),
        SupportedLanguage(code: "en", name: "English"),
        SupportedLanguage(code: "es", name: "Spanish"),
        SupportedLanguage(code: "et", name: "Estonian"),
        SupportedLanguage(code: "fa", name: "Persian"),
        SupportedLanguage(code: "fi", name: "Finnish"),
        SupportedLanguage(code: "fr", name: "French"),
        SupportedLanguage(code: "gl", name: "Galician"),
        SupportedLanguage(code: "he", name: "Hebrew"),
        SupportedLanguage(code: "hi", name: "Hindi"),
        SupportedLanguage(code: "hr", name: "Croatian"),
        SupportedLanguage(code: "hu", name: "Hungarian"),
        SupportedLanguage(code: "id", name: "Indonesian"),
        SupportedLanguage(code: "it", name: "Italian"),
        SupportedLanguage(code: "ja", name: "Japanese"),
        SupportedLanguage(code: "kk", name: "Kazakh"),
        SupportedLanguage(code: "ko", name: "Korean"),
        SupportedLanguage(code: "lt", name: "Lithuanian"),
        SupportedLanguage(code: "lv", name: "Latvian"),
        SupportedLanguage(code: "mk", name: "Macedonian"),
        SupportedLanguage(code: "ml", name: "Malayalam"),
        SupportedLanguage(code: "mr", name: "Marathi"),
        SupportedLanguage(code: "ms", name: "Malay"),
        SupportedLanguage(code: "nl", name: "Dutch"),
        SupportedLanguage(code: "no", name: "Norwegian"),
        SupportedLanguage(code: "pl", name: "Polish"),
        SupportedLanguage(code: "pt", name: "Portuguese"),
        SupportedLanguage(code: "ro", name: "Romanian"),
        SupportedLanguage(code: "ru", name: "Russian"),
        SupportedLanguage(code: "sk", name: "Slovak"),
        SupportedLanguage(code: "sl", name: "Slovenian"),
        SupportedLanguage(code: "sr", name: "Serbian"),
        SupportedLanguage(code: "sv", name: "Swedish"),
        SupportedLanguage(code: "sw", name: "Swahili"),
        SupportedLanguage(code: "ta", name: "Tamil"),
        SupportedLanguage(code: "te", name: "Telugu"),
        SupportedLanguage(code: "th", name: "Thai"),
        SupportedLanguage(code: "tl", name: "Tagalog"),
        SupportedLanguage(code: "tr", name: "Turkish"),
        SupportedLanguage(code: "uk", name: "Ukrainian"),
        SupportedLanguage(code: "ur", name: "Urdu"),
        SupportedLanguage(code: "vi", name: "Vietnamese"),
        SupportedLanguage(code: "zh", name: "Chinese"),
    ]

    // Legacy alias for backward compatibility
    static let allLanguages: [SupportedLanguage] = cloudLanguages

    static func language(for code: String) -> SupportedLanguage? {
        cloudLanguages.first(where: { $0.code == code })
    }
}
