# SwiftLint configuration

excluded:
  - .build
  - Diduny.xcodeproj
  - Diduny.app

# Disable rules that conflict with API response models using snake_case
identifier_name:
  excluded:
    - i
    - x
    - y
    - id
    # API response field names (snake_case from JSON)
    - created_at
    - client_reference_id
    - error_message
    - error_type
    - start_ms
    - end_ms
    - translation_status
    - source_language

# Relax line length for long URLs and API code
line_length:
  warning: 150
  error: 250
  ignores_urls: true
  ignores_comments: true

# Relax body length limits
file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 400
  error: 800

function_body_length:
  warning: 80
  error: 150

cyclomatic_complexity:
  warning: 15
  error: 30

# Disable trailing comma rule (SwiftFormat adds them)
disabled_rules:
  - trailing_comma

# Enable useful opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call
