name: Diduny
options:
  bundleIdPrefix: ua.com.rmarinsky
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  DynamicNotchKit:
    url: https://github.com/MrKai77/DynamicNotchKit
    from: 1.0.0
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: 1.0.0

configs:
  Debug: debug
  Test: release
  Release: release

settings:
  base:
    MARKETING_VERSION: "1.6.1"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "8JL9TM5WLG"
    CODE_SIGN_STYLE: Automatic
    ARCHS: "arm64 x86_64"
    ENABLE_HARDENED_RUNTIME: YES
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
    Test:
      ONLY_ACTIVE_ARCH: NO
    Release:
      ONLY_ACTIVE_ARCH: NO

configFiles:
  Debug: Config/Debug.xcconfig
  Test: Config/Test.xcconfig
  Release: Config/Release.xcconfig

targets:
  Diduny:
    type: application
    platform: macOS
    sources:
      - path: Diduny
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: KeyboardShortcuts
      - package: DynamicNotchKit
      - package: LaunchAtLogin
    settings:
      base:
        INFOPLIST_FILE: Diduny/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Diduny/Resources/Diduny.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
      configs:
        Debug:
          PRODUCT_NAME: "Diduny DEV"
          PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.diduny.dev
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV_BUILD DEBUG
        Test:
          PRODUCT_NAME: "Diduny TEST"
          PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.diduny.test
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST_BUILD
        Release:
          PRODUCT_NAME: "Diduny"
          PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.diduny
    entitlements:
      path: Diduny/Resources/Diduny.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

schemes:
  Diduny DEV:
    build:
      targets:
        Diduny: all
    run:
      config: Debug
    archive:
      config: Debug

  Diduny TEST:
    build:
      targets:
        Diduny: all
    run:
      config: Test
    archive:
      config: Test

  Diduny:
    build:
      targets:
        Diduny: all
    run:
      config: Release
    archive:
      config: Release
