name: DictateToBuffer
options:
  bundleIdPrefix: ua.com.rmarinsky
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0

settings:
  base:
    MARKETING_VERSION: "1.2.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "8JL9TM5WLG"
    CODE_SIGN_STYLE: Automatic
    ARCHS: "arm64 x86_64"
    ONLY_ACTIVE_ARCH: NO
    ENABLE_HARDENED_RUNTIME: YES

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

targets:
  DictateToBuffer:
    type: application
    platform: macOS
    sources:
      - path: DictateToBuffer
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: KeyboardShortcuts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.dictatetobuffer
        INFOPLIST_FILE: DictateToBuffer/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: DictateToBuffer/Resources/DictateToBuffer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
    entitlements:
      path: DictateToBuffer/Resources/DictateToBuffer.entitlements
      properties:
        com.apple.security.device.audio-input: true

  DictateToBuffer-Test:
    type: application
    platform: macOS
    sources:
      - path: DictateToBuffer
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: KeyboardShortcuts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ua.com.rmarinsky.dictatetobuffer.test
        PRODUCT_NAME: "DictateToBuffer Test"
        INFOPLIST_FILE: DictateToBuffer/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: DictateToBuffer/Resources/DictateToBuffer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: TEST_BUILD
    entitlements:
      path: DictateToBuffer/Resources/DictateToBuffer.entitlements
      properties:
        com.apple.security.device.audio-input: true
